### ISSUE TITLE
Twitter access forbidden

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/strands_utils#52]
i am having problems with automatic tweeting messages on twitter. I did all the instructions as described in the readme file, but get the error:

```
rosrun strands_tweets tweet.py
[INFO] [WallTime: 1385368224.427726] Ready to Tweet ...
[INFO] [WallTime: 1385368261.069870] Tweeting This is a test. ... (15)
Twitter API returned a 403 (Forbidden), Status is a duplicate.

```

or

```
rosservice call /strands_tweets/Tweet 'This is a test.' false
result: False
```

Any quick suggestion?

**Comment by Jailander** [comment]
The problem is that twitter doesn't allow to tweet the same thing twice, you have to change the message every time

**Comment by ToMadoRe** [comment]
okay, now it says "result: True" but there is no new message on the Twitter account

**Comment by Jailander** [comment]
I guess its here https://twitter.com/SimLindaStrands, It's because you have to change your access keys and tokens, you can see how in here https://github.com/strands-project/strands_utils/blob/master/strands_tweets/README.md

**Comment by Jailander** [comment]
If your keys arenot being updated try rosparam load "the yaml file with your twitter keys" and then save the parameters like the README says

**Comment by ToMadoRe** [comment]
I did change the parameters in /opt/strands/strands_catkin_ws/src/strands_utils/strands_datacentre/twitter_params.yaml and called all the rosservices. But still it publishes on the wrong Twitter account. I also tried to call `rosparam load '/opt/strands/strands_catkin_ws/src/strands_utils/strands_datacentre/defaults/twitter_params.yaml` but no success

**Comment by ToMadoRe** [comment]
Let me just show you the .yaml file so that you can check if i used the right values:
dev.twitter.com/apps says:

```
Consumer key    wRy2Zuh8NLFcguAwHVKn1A
Consumer secret jhNw600ooZzTlVN6rbf7SuvOkVjpjNJNixxCl8SuQ
Access token    2150582455-TXmdoa2owKdaCy0LB9lOj8VW2mvcbD6yFMAFxvD
Access token secret m9zA3GbLyYAHIuvyPkglTDyj41ZgsKtNNlqmJqSPfqSMQ
```

and the yaml file is

```
twitter:
  appKey: 'wRy2Zuh8NLFcguAwHVKn1A'
  appSecret: 'jhNw600ooZzTlVN6rbf7SuvOkVjpjNJNixxCl8SuQ'
  oauthToken: '2150582455-TXmdoa2owKdaCy0LB9lOj8VW2mvcbD6yFMAFxvD'
  oauthTokenSecret: 'm9zA3GbLyYAHIuvyPkglTDyj41ZgsKtNNlqmJqSPfqSMQ'
```
